---
- name: Deploy Scientific Calculator Docker Container
  hosts: localhost
  tasks:
    - name: Stop and remove any existing container
      community.docker.docker_container:
        name: "scientific-calculator-app"
        state: absent

    - name: Pull the latest Docker image
      community.docker.docker_image:
        name: "sarvesh717/scientific-calculator:latest"
        source: pull

    - name: Run the application container in the background
      community.docker.docker_container:
        name: "scientific-calculator-app"
        image: "sarvesh717/scientific-calculator:latest"
        state: started
        detach: yes
        # This command keeps the container running so you can access it later
        command: tail -f /dev/null