---
- name: Deploy Scientific Calculator Docker Container
  hosts: localhost
  tasks:
    - name: Stop and remove any existing container
      ansible.builtin.shell: "docker stop sci-calc ; docker rm sci-calc"
      ignore_errors: yes

    - name: "TEST: Read test.txt after container stop"
      ansible.builtin.shell: "cat test.txt"
      register: cat_output_1
    - name: "TEST: Display output 1"
      ansible.builtin.debug:
        var: cat_output_1.stdout

    - name: Pull the latest Docker image
      ansible.builtin.shell: "docker pull sarvesh717/scientific-calculator:latest"

    - name: "TEST: Read test.txt after image pull"
      ansible.builtin.shell: "touch test1.txt"

    - name: Run the container in the background using shell
      ansible.builtin.shell: >
        docker run -d 
        --name "sci-calc"
        sarvesh717/scientific-calculator:latest
        tail -f /dev/null
    
    - name: "TEST: Read test.txt after container run"
      ansible.builtin.shell: "cat test.txt"
      register: cat_output_3
    - name: "TEST: Display output 3"
      ansible.builtin.debug:
        var: cat_output_3.stdout